server:
  port: 8033
spring:
  application:
    name: food-trucks
mybatis:
  mapper-locations: classpath:mapper/*.xml

spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.01:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.hikari.max-lifetime: 120000