-- test.mobilefoodfacilitypermit definition

CREATE TABLE `mobilefoodfacilitypermit` (
  `id` int NOT NULL AUTO_INCREMENT,
  `location_id` int DEFAULT NULL,
  `applicant` varchar(128) DEFAULT NULL,
  `facility_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `cnn` int DEFAULT NULL,
  `location_description` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `address` varchar(50) DEFAULT NULL,
  `blocklot` varchar(50) DEFAULT NULL,
  `block` varchar(50) DEFAULT NULL,
  `lot` varchar(50) DEFAULT NULL,
  `permit` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `food_items` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `x` double DEFAULT NULL,
  `y` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `schedule` varchar(256) DEFAULT NULL,
  `dayshours` varchar(50) DEFAULT NULL,
  `noi_sent` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `approved` varchar(50) DEFAULT NULL,
  `received` int DEFAULT NULL,
  `prior_permit` int DEFAULT NULL,
  `expiration_date` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `location` varchar(50) DEFAULT NULL,
  `fire_prevention_districts` int DEFAULT NULL,
  `police_districts` int DEFAULT NULL,
  `supervisor_districts` int DEFAULT NULL,
  `zip_codes` int DEFAULT NULL,
  `neighborhoods_old` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=478 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;